// pages/components/Layout.js
import Head from 'next/head';
import React from 'react';
import { NavigationBar } from './NavigationBar';

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Abraham Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[100vh] max-w-[100vw]">
        <div className="flex flex-col bg-[#15181b] min-h-screen">
            <NavigationBar />
            <div className="flex-1 bg-[#333] w-[80vw] m-auto">
                {children}
            </div>
        </div>
      </main>
    </>
  );
}
