// pages/components/Layout.js
import Head from 'next/head';
import React from 'react';
import { NavigationBar } from './NavigationBar';
import { ContactButtons } from './ContactButtons';

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Abraham Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full w-full bg-gray-700">
        <NavigationBar />
        <div className="overflow-hidden h-[100%] relative z-10">
          <div className="hidden md:block">
            <ContactButtons />
          </div>
          <div className="absolute top-0 bg-primary-500 min-h-[16rem] md:min-h-[18rem] min-w-[100%] max-w-[100%] -z-10">
            <div className="absolute top-[16rem] md:top-[18rem] h-[190px] w-[6000px] bg-wave animate-wave-1 bg-bottom"></div>
            <div className="absolute top-[17.5rem] md:top-[19rem] left-0 h-[190px] w-[6000px] bg-wave animate-wave-2 bg-bottom opacity-50"></div>
          </div>
          <div className="absolute bottom-0 bg-primary-500 min-h-[1rem] md:min-h-[1rem] min-w-[100%] max-w-[100%] -z-10">
            <div className="absolute top-[-10rem] rotate-180 md:top-[-10rem] h-[190px] w-[5500px] bg-wave animate-wave-1 bg-bottom"></div>
            <div className="absolute top-[-11.5rem] md:top-[-11rem] left-0 h-[190px] w-[5500px] bg-wave-bottom animate-wave-2 bg-bottom opacity-50"></div>
          </div>
          {/* <div className="absolute bg-bottom bottom-0 min-w-[100vw] max-w-[100vw]" style={{minHeight: "43rem"}}>
          </div> */}
          <div className="w-full md:w-[70vw] md:m-auto min-h-[90vh] md:min-h-[100vh]">
            {children}
          </div>
        </div>
          {/* <div className="overflow-hidden pb-5">
            <div className="relative">
              <div className="bg-[#028ac7]">
                {children}
              </div>
              <div className="left-0 top-0 h-[16rem] w-[900px] animate-wave-1 bg-wave bg-bottom"></div>
              <div className="absolute bottom-0 left-0 h-[18rem] w-[1000px] animate-wave-2 bg-wave bg-bottom opacity-50"></div>
            </div>
          </div> */}
        {/* <div className="flex flex-col bg-[#15181b] min-h-screen bg-wave animate-wave-1 top-0 h-1/2 -z-10"></div> */}
      </main>
    </>
  );
}

// <section id="intro">
//   <div className="overflow-hidden pb-5">
//     <div className="relative">
//       <div className="bg-primary-500">
//         <div className="container mx-auto grid grid-cols-2 justify-items-center gap-y-20 px-2 py-20 sm:px-4">
//           <div className="col-span-2 w-[255px] lg:col-span-1">
//             <h1 className="text-6xl font-bold leading-tight drop-shadow-xl">Lucas <br>Facu</h1>
//             <span className="text-xl font-light uppercase leading-10" data-testid="react-typed">
//               <span>front-end developer</span>
//               <span className="typed-cursor typed-cursor--blink" aria-hidden="true">|</span>
//             </span>
//           </div>
//           <div className="col-span-2 animate-move-y lg:col-span-1">
//             <figure className="h-56">
//               <img src="img/hero.svg" alt="" className="h-full">
//             </figure>
//           </div>
//         </div>
//       </div>
//       <div className="left-0 h-[150px] w-[6000px] animate-wave-1 bg-wave bg-bottom"></div>
//       <div className="absolute bottom-0 left-0 h-[150px] w-[6000px] animate-wave-2 bg-wave bg-bottom opacity-50"></div>
//     </div>
//   </div>
// </section> 